baseURL = "http://example.org/"
themeDir = "themes"
languageCode = "en-us"
title = "District Zouk"
theme = "landing-page-hugo"
canonifyUrls = "true"

[params]
    description = "Washington DC's leading source for Brazilian Zouk classes, socials, & events"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:bushbama@whitehouse.gov"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://www.facebook.com/DistrictZouk/"
