backend:
  name: git-gateway
  repo: cryberg/district-zouk
  branch: master
  publish_mode: editorial_workflow

media_folder: static/img

collections:
  - name: post
    label: Post
    folder: content/post
    create: true
    fields:
      - {name: title, label: Title, widget: string, tagname: h2}
      - {name: img, label: Image, widget: image}
      - {name: weight, label: Weight, widget: number}
      - {name: body, label: Body, widget: markdown}
